language: node_js
node_js:
- "0.12"
script: npm run test
deploy:
  provider: heroku
  skip_cleanup: true
  before_deploy: npm run build
  api_key: NAdomV9c4ZSj4BMhJZLplPbGEu6+cYK7YMuWitd9Sw5CSNdMc/TqJoI2QjncVdWoV0mry4+LU+CKHsljYMsFxWe0JAJ7h0hKbyghK8iRwziaqHnvYJWZpnO+jeCdU/TFrfF44xI9+C9nwZvtd5I7tMh8C/69U3fIJlwDB53v+SDEsoXBkk+wWN9RgpcG9Ant2+7IkbZM95CJqU2604tACNVVoRF0b6Kb3tsWJ+Sf+sVshDf2l5XxoiHq8jijn+pwwI8CooZgtjyHWdByHAq8WMI081r9e7qWqN5LqDjJ4uf3S7CmWCiNgMjzdTJVm+z9jKJt5wSj1X2QZSBjtLGtPdpOVlxN6WsX0bntvXfkP66VbR3TrA7jgNsS/RBjQlnk8InRGW6tH+zOtj+UhoEsMErdTtnzBkYDF+yLcoGWwJYwQN3H1qg8PseIcjepgJFtF0sZMnWbZ0KQSArKJGygzhKjiokmE2hLYp5qowz48EexejxTWlrbAkxA9hhNMGFZJJFWqBU7GP0dUaMO9zcC8GUCp97NMWV4Wm5D2oVeAGd3LwRui2ymiK+pX2nfq93FaPTAEOGaelfVWm/+WbEKZuiRtYxB5pxDF5CPO/W9iAkm8sgdBtQESiZRYXHqvlnc6VusNnINJ7lQrcIjEhqk5MHtoh+RBuMMd29avXPn7yI=
  on:
    branch: add-url-support
