language: node_js
node_js:
- "0.12"
script: npm run test
env:
  global:
  - GH_REF: github.com/cherta/apis-uy.git
  - secure: "qYmBkiC0Wm3Js+dF32AROZjEQ5QAPLdA/jw39rgDChXUGAhctdE/dN0Rz1ZHk4Ypqo5e+V/O/rHJ8rdLjgyeHtgR37pVQwENLHwAEVL+hHbs+I9SjRtH7OgLur/pwVS8CkHbTTuo4rrcpmgofxWBaWLsbDBdO9oraS7KAeB/orRPkMUG2a8W/DBewKrLNVuJSlS1Td/KUdoGYbKBU1803VDDHp3r10vWY1n9xUkzb2Fj6IwPol0aEqV2j2qUOi6VxTRmwolurO/cXOiqxJqaRvOXagov+pQEkKK4YA7ngDQMaMRLXEopvKxNDdiVofR+noNiGCY0cybu3WO52ZimKwgAqaYQ5rN08ho3MfSnOJa1ToldWfyUlVsuYmFowMymX9uq2ynJAZRd2D+qsj2pAvhyuHZHO4n4JwA9WIrPqIb8S62AyBctLmQ2zR54ZM63mkQ1+hAN9GSXH1OGFOvzEl8ck0FwT029WQmmjHPLZmQ6sFiqXzHpviux5aC4inSbf2v3SWBulGUC+aWf+1JgV+dZ2ct56/A9fgnJnNg3OQVVC8BcG1Ess2MV1Z061L0FGlN8TxvtDYdKGiaWopf0KJPFb5+ER3rQUXXZtvanWQBY7hbztks9YmN4USXjVtmauXAs6+J0p+OuQ3ZEo9mE/iy4IYjaUK39LTYytIVPxzA="
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  on:
    branch: master
